config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :books
    resources :chapters
    resources :decision_points
    resources :parts
    resources :genres
    resources :libraries
    resources :reviews
    resources :shelves
    resources :answers
    resources :progresses

    root to: "users#index"
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :books do
    resources :chapters do
      resources :parts do
        resources :decision_points
      end
    end
    resources :reviews, except: [:index, :show]
    get 'search', on: :collection
    get 'details', on: :member
    get 'read(/:part_id)', action: :read, on: :member, as: 'read'
    match 'add_to_library', action: :add_to_library, on: :member, via: [:get, :post]
    delete 'remove_from_library', on: :member
    get 'browse', on: :collection
  end

  resources :shelves, except: [:index]
  resources :genres, only: [:index, :show]

  root to: 'home#index'
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :books
end

app/controllers/admin/genres_controller.rb
module Admin
  class GenresController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Genre.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Genre.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.includes(:books).order(name: :asc)
  end

  def show
    @books = genre.books.decorate
  end

  private

  def genre
    @genre ||= Genre.find(params[:id])
  end
end

app/views/genres/_genre_card.html.haml
.col-sm-3.section
  = link_to genre_path(genre), class: 'genre__card' do
    .card.genre__card
      .card-block.text-xs-center
        %h3.card-title.genre__name
          = genre.name
        %h4.cart-subtitle.text-muted.genre__book-count
          = genre.books.size
        %p.card-text.genre__description
          = genre.description

app/views/genres/index.html.haml
.row
  .col.sm-12
    %h2 Browse genres
.row
  - @genres.each do |genre|
    = render partial: 'genre_card', locals: { genre: genre }

app/views/genres/show.html.haml
.row
  .col.sm-12
    %h2 #{@genre.name}
.row
  - @books.each do |book|
    = render partial: 'books/book_card', locals: { book: book }