config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :books
    resources :chapters
    resources :decision_points
    resources :parts
    resources :genres
    resources :libraries
    resources :reviews
    resources :shelves
    resources :answers
    resources :progresses

    root to: "users#index"
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :books do
    resources :chapters do
      resources :parts do
        resources :decision_points
      end
    end
    resources :reviews, except: [:index, :show]
    get 'search', on: :collection
    get 'details', on: :member
    get 'read(/:part_id)', action: :read, on: :member, as: 'read'
    match 'add_to_library', action: :add_to_library, on: :member, via: [:get, :post]
    delete 'remove_from_library', on: :member
    get 'browse', on: :collection
  end

  resources :shelves, except: [:index]
  resources :genres, only: [:index, :show]

  root to: 'home#index'
end

app/models/part.rb
class Part < ApplicationRecord
  default_scope { includes(decision_point: [:answers]) }

  belongs_to :chapter
  has_one :decision_point
  has_many :progresses
end

app/controllers/admin/parts_controller.rb
module Admin
  class PartsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Part.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Part.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  def index
    @parts = Part.where(chapter: chapter).decorate
  end

  def show
    part
  end

  def new
    @part = new_part_form
  end

  def create
    @part = new_part_form
    if @part.validate(params[:part])
      @part.save do |data|
        @part = Part.create(data)
        flash[:notice] = 'Part successfully created'
        redirect_to new_book_chapter_part_decision_point_path(@book, @chapter, @part)
      end
    else
      render :new
    end
  end

  def edit
    @part = edit_part_form
  end

  def update
    @part = edit_part_form
    if @part.validate(params[:part])
      @part = @part.sync
      @part.save
      flash[:notice] = 'Part successfully updated'
      redirect_to edit_book_chapter_part_decision_point_path(@book, @chapter, @part)
    else
      render :edit
    end
  end

  def destroy
    if part.destroy
      flash[:notice] = 'Part successfully deleted'
      redirect_to book_chapter_parts(book, chapter)
    end
  end

  private

  def part
    chapter
    @part ||= Part.find(params[:id])
  end

  def chapter
    book
    @chapter ||= Chapter.find(params[:chapter_id])
  end

  def book
    @book ||= Book.find(params[:book_id])
  end

  def new_part_form
    part = Part.new(chapter: chapter)
    PartForm.new(part)
  end

  def edit_part_form
    PartForm.new(part)
  end
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/parts/add_answer.js.erb
$('#answer__fields').append("<%= j render('answer_field', counter: @counter) %>");

app/views/parts/edit.html.haml
.container
  .row
    .col-sm-12
      %h2 Create new part
      = simple_form_for [@book, @chapter, @part] do |f|
        .row
          .col-sm-12
            .form-group
              = f.input :title
          .col-sm-12
            .form-group
              = f.input :content, as: :text, input_html: { class: 'tinymce', rows: 20 }
              = tinymce
        .row
          .col-sm-12
            = f.submit 'Edit part', class: 'btn btn-success'

app/views/parts/index.html.haml
.container
  .row
    .col-sm-9
      %h2 Parts
    .col.sm-3.pull-right
      = link_to 'Create new part', new_book_chapter_part_path(@book, @chapter), class: 'btn btn-outline-primary'
  .row
    .col-sm-12
      %table.table.table-hover
        %thead.thead-inverse
          %tr
            %th #
            %th
              = Part.human_attribute_name :title
            %th
              = Part.human_attribute_name :content
            %th
              = Part.human_attribute_name :created_at
            %th
              = Part.human_attribute_name :actions
        %tbody
          - @chapter.parts.each do |part|
            %tr
              %th{ scope: 'row' }
                = part.id
              %td
                = link_to part.title, [@book, @chapter, part]
              %td.table__cell-centered
                = part.content.html_safe
              %td
                = part.created_at
              %td.table__cell-centered.table__actions
                = link_to fa_icon('search'), [@book, @chapter, part], class: 'actions__button'
                = link_to fa_icon('edit'), edit_book_chapter_part_path(@book, @chapter, part), class: 'actions__button'
                = link_to fa_icon('times'), book_chapter_part_path(@book, @chapter, part), method: :delete, class: 'actions__button actions__button-aligned'

app/views/parts/new.html.haml
.container
  .row
    .col-sm-12
      %h2 Create new part
      = simple_form_for [@book, @chapter, @part] do |f|
        .row
          .col-sm-12
            .form-group
              = f.input :title
          .col-sm-12
            .form-group
              = f.input :content, as: :text, input_html: { class: 'tinymce', rows: 20 }
              = tinymce
        .row
          .col-sm-12
            = f.submit 'Create part', class: 'btn btn-success'