config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :books
    resources :chapters
    resources :decision_points
    resources :parts
    resources :genres
    resources :libraries
    resources :reviews
    resources :shelves
    resources :answers
    resources :progresses

    root to: "users#index"
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :books do
    resources :chapters do
      resources :parts do
        resources :decision_points
      end
    end
    resources :reviews, except: [:index, :show]
    get 'search', on: :collection
    get 'details', on: :member
    get 'read(/:part_id)', action: :read, on: :member, as: 'read'
    match 'add_to_library', action: :add_to_library, on: :member, via: [:get, :post]
    delete 'remove_from_library', on: :member
    get 'browse', on: :collection
  end

  resources :shelves, except: [:index]
  resources :genres, only: [:index, :show]

  root to: 'home#index'
end

app/views/partials/_home.html.haml
.row
  .col-sm-6.offset-sm-3
    Welcome to WebBooks - the first platform for creating brand new type of books.
    %h3.home__header What is WebBook?
    Basically, webbook is a book created and read through the Web. It's the next step in the books evolution. It contains following:
    %ul.home__content
      %li
        traditional
        %strong book
        in its digital form
      %li
        %strong gamebooks
        \- books where you (as a reader) can choose what happens next and you (as a writer) can define multiple plot lines
      %li
        %strong multimedia
        \- images, movies, whatever you can dream of to make your reading experience better.

app/views/partials/_navbar.html.haml
%nav.navbar.navbar-full.navbar-dark.bg-inverse
  = link_to 'WebBooks', root_path, class: 'navbar-brand'
  - if @book
    %ul.nav.navbar-nav.book__details.hidden-sm-down
      %li.nav-item.book__details-title
        = @book.title
      %li.nav-item.book__details-subtitle
        = @book.subtitle
  %ul.nav.navbar-nav.pull-xs-right
    - if user_signed_in?
      %li.nav-item
        = link_to current_user.profile_link_text, root_path, class: 'nav-link'
      %li.nav-item
        = link_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-warning'
    - else
      %li.nav-item
        = link_to 'Sign up', new_user_registration_path, class: 'btn btn-outline-success'
      %li.nav-item
        = link_to 'Sign in', new_user_session_path, class: 'btn btn-outline-secondary'

app/views/partials/_reader_page.html.haml
.row
  .col-sm-4.book__links
    = link_to 'Add new shelf', new_shelf_path, class: 'btn btn-outline-primary'
    = link_to 'Browse books', browse_books_path, class: 'btn btn-outline-primary'
  .col-sm-8.book__search
    = render partial: 'books/search_form'
.row
  .col-sm-12
    %h3.library__header Your Library
    .row
    - current_user.shelves.each do |shelf|
      .col-sm-4.section
        .card.shelf
          = link_to shelf do
            .card-block.text-xs-center
              %h3.card-title
                = shelf.name
              %p.card-text
                = shelf.description

app/views/partials/_writer_page.html.haml
.row
  .col-sm-4.section
    .card
      = image_tag 'book.jpg', class: 'card-img-top card-image'
      .card-block.text-xs-center
        %h3.card-title Your books
        %p.card-text Manage your books.
        - if current_user.books.empty?
          = link_to "You don't have any books... yet", books_path, class: 'btn btn-outline-primary disabled'
        - else
          %p.card-text You wrote #{current_user.books.count} books.
          = link_to 'Show books', books_path, class: 'btn btn-outline-primary'
  .col-sm-4.section
    .card
      = image_tag 'typewriter.jpg', class: 'card-img-top card-image'
      .card-block.text-xs-center
        %h3.card-title New book
        %p.card-text Create new book
        = link_to 'Start writing', new_book_path, class: 'btn btn-outline-primary'
  .col-sm-4.section
    .card
      = image_tag 'library.jpg', class: 'card-img-top card-image'
      .card-block.text-xs-center
        %h3.card-title Statistics
        %p.card-text Here you will be able to check statistics about your works of art.
        %button.btn.btn-outline-primary{disabled: true} Check some numbers